# How to use BSF
## Check prerequisites
- Install the BSF python package (https://github.com/PNNL-Comp-Mass-Spec/bsf-py)
- Check the installation

In [1]:
# import the BSF library
import bsf

In [2]:
# generate random matrix with uint64
import numpy as np

nsign = 9  # the number of signatures
nquery = 5  # the number of queries
length = 12  # a length of a signature
# a library matrix
lmat = np.random.randint(2, size=(nsign, length)).astype(np.uint64)
lmat

array([[1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1],
       [0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0],
       [0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1],
       [0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1],
       [1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0],
       [1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1],
       [1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0]], dtype=uint64)

In [3]:
# Run BSF to compute the pairwise similiarity of all the pairs of matrix
bsf.analysis_with_chunk(lmat, nsign, 'bsf.txt', '/Users/leej324/Documents/projects/')

1

In [4]:
# read a result table (binary file)
with open("/Users/leej324/Documents/projects/bin_9_0_0_9_9_bsf.txt.bin", "rb") as f:
    rst_mat = np.frombuffer(f.read(), dtype=np.uint32).reshape((nsign, nsign))
rst_mat

array([[0, 4, 5, 5, 3, 4, 2, 3, 4],
       [0, 0, 5, 4, 5, 5, 3, 3, 4],
       [0, 0, 0, 5, 4, 5, 3, 3, 5],
       [0, 0, 0, 0, 4, 5, 2, 1, 2],
       [0, 0, 0, 0, 0, 5, 3, 4, 3],
       [0, 0, 0, 0, 0, 0, 3, 3, 3],
       [0, 0, 0, 0, 0, 0, 0, 3, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint32)

In [5]:
# generate query matrix
qmat = np.random.randint(2, size=(nquery, length)).astype(np.uint64)

In [6]:
bsf.analysis_with_query(lmat, qmat, 'qbsf.txt', '/Users/leej324/Documents/projects/')

1

In [7]:
print(lmat)
print(qmat)

[[1 1 1 0 0 1 0 1 1 0 0 1]
 [0 1 0 1 1 1 0 1 1 0 1 0]
 [0 1 1 0 1 1 1 1 1 1 0 0]
 [0 0 1 1 0 1 0 1 1 1 0 1]
 [0 0 0 1 1 0 1 1 1 0 1 1]
 [1 0 1 1 1 0 0 1 1 1 1 0]
 [0 1 1 1 0 0 1 0 0 0 1 0]
 [1 1 0 0 1 0 1 0 0 0 1 1]
 [1 1 0 0 1 1 1 0 1 0 0 0]]
[[0 1 0 0 0 0 1 0 0 1 1 1]
 [1 0 1 0 0 1 0 1 1 1 1 1]
 [1 1 1 0 0 1 0 0 1 1 0 0]
 [1 1 1 0 0 1 1 0 0 0 1 1]
 [0 1 1 0 1 1 1 0 1 1 0 1]]


In [8]:
# read a result table (binary file)
with open("/Users/leej324/Documents/projects/bin_qbsf.txt.bin", "rb") as f:
    rst_mat = np.frombuffer(f.read(), dtype=np.uint32).reshape((nsign, nquery))
rst_mat

array([[2, 6, 5, 5, 5],
       [2, 4, 3, 3, 4],
       [3, 5, 5, 4, 7],
       [2, 6, 4, 3, 5],
       [3, 4, 1, 3, 4],
       [2, 6, 4, 3, 4],
       [3, 2, 2, 4, 3],
       [4, 3, 2, 5, 4],
       [2, 3, 4, 4, 5]], dtype=uint32)